# Generated by Django 3.1.1 on 2020-09-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': 'links'},
        ),
    ]
